title: PyJupiter
email: luizeleno@usp.br
description: >- # this means to ignore newlines until "baseurl:"
  Raspagem dos cursos da EEL-USP no  Júpiter
baseurl: /pyjupiter # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  
google_analytics: G-J42QBMBTBB

plugins:
  - jekyll-datapage-generator

destination: docs/

exclude:
  - Rakefile
  - README.md
  - LICENSE
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/

gems: 
- jekyll-octicons

page_gen:

- data: 'disciplinas'
  template: 'disciplina-page'
  name: 'sigla'
  dir: 'disciplinas'
